name: My Demo

on:
  push:
    branches:
      - main

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set nodejs version to 18.x 
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run format
        run: npm run format

      - name: Run Build Production(create dist folder)
        run: npm run build
